//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Light.Args {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Light.Args.RE", typeof(RE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the argument &quot;{0}&quot; is not bool type..
        /// </summary>
        internal static string ArgumentIsNotBoolType {
            get {
                return ResourceManager.GetString("ArgumentIsNotBoolType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to argument &quot;{0}&quot; value can not empty..
        /// </summary>
        internal static string ArgumentValueIsNull {
            get {
                return ResourceManager.GetString("ArgumentValueIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can not find argument name &quot;{0}&quot;..
        /// </summary>
        internal static string CanNotFindArgumentName {
            get {
                return ResourceManager.GetString("CanNotFindArgumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default member must string array type..
        /// </summary>
        internal static string DefaultMemberMustStringArray {
            get {
                return ResourceManager.GetString("DefaultMemberMustStringArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parse argument &quot;{0}&quot; error..
        /// </summary>
        internal static string ParseArgumentError {
            get {
                return ResourceManager.GetString("ParseArgumentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can not parse the boolean format &quot;{0}&quot;..
        /// </summary>
        internal static string ParseBooleanError {
            get {
                return ResourceManager.GetString("ParseBooleanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can not parse the datetime format &quot;{0}&quot;..
        /// </summary>
        internal static string ParseDateTimeError {
            get {
                return ResourceManager.GetString("ParseDateTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can not parse the {1} format &quot;{0}&quot;..
        /// </summary>
        internal static string ParseNumberError {
            get {
                return ResourceManager.GetString("ParseNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unable the value is null..
        /// </summary>
        internal static string UnableNull {
            get {
                return ResourceManager.GetString("UnableNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unsupport the type &quot;{0}&quot;..
        /// </summary>
        internal static string UnsupportType {
            get {
                return ResourceManager.GetString("UnsupportType", resourceCulture);
            }
        }
    }
}
